version: 1
disable_existing_loggers: 'TRUE'
formatters:
  simple:
    format: '%(asctime)s [%(levelname)s] %(filename)s-%(lineno)d: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: 'ext://sys.stdout'
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 10485760
    backupCount: 50
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  __main__:
    level: INFO
    handlers:
      - info_file_handler
      - error_file_handler
    propagate: 'no'
  DEBUG:
    level: DEBUG
    handlers:
      - console
      - info_file_handler
      - error_file_handler
    propagate: 'no'